import { StyleSheet } from "react-native";
import colors from "./Colors";
import themeFontSize from "./themeFontSizes";

export default StyleSheet.create({
  wrapper: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: colors.white,
    paddingHorizontal: "7%",
  },
  wrapperDark: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: colors.darkPrimary,
    paddingHorizontal: "7%",
  },
  text: {
    // fontFamily: "PoppinsLight",
    fontSize: themeFontSize.small,
    color: colors.black,
  },
  redText: { color: colors.red },
  drawerHeader: {
    top: 17,
    position: "absolute",
    height: 60,
    alignSelf: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    left: 21,
    right: 21,
    // marginVertical: 17,
  },
  drawerProfile: {
    resizeMode: "cover",
    height: 50,
    width: 50,
    borderRadius: 25,
  },
  headerText: {
    fontSize: themeFontSize.medium,
    fontWeight: "400",
    color: colors.white,
    paddingVertical: 3,
  },
  drawerHeading: {
    fontSize: themeFontSize.xl,
    fontWeight: "700",
    color: colors.white,
    marginTop: "11%",
    marginBottom: 22,
    marginHorizontal: 21,
  },
  drawerChild: {
    height: "5%",
    // alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-around",
    marginHorizontal: 24,
    marginVertical: 11,
    borderBottomWidth: 1,
    borderColor: colors.gray,
  },
  menuText: {
    fontSize: themeFontSize.medium,
    fontWeight: "400",
    color: colors.white,
    // paddingVertical: 3,
    // marginHorizontal: 21,
  },
  h1: {
    // fontFamily: "PoppinsRegular",
    fontSize: themeFontSize.xxl,
  },
  h1Bold: {
    // fontFamily: "PoppinsRegular",
    fontWeight: "bold",
    fontSize: themeFontSize.xxl,
  },
  h2: {
    // fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.xl,
  },
  h2Bold: {
    // fontFamily: "PoppinsMedium",
    fontWeight: "bold",
    fontSize: themeFontSize.xl,
  },
  h3: {
    // fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.large,
  },
  h3Bold: {
    // fontFamily: "PoppinsMedium",
    fontWeight: "bold",
    fontSize: themeFontSize.large,
  },
  h4: {
    // fontFamily: "PoppinsRegular",
    fontSize: themeFontSize.medium,
  },
  h4Bold: {
    // fontFamily: "PoppinsRegular",
    fontWeight: "bold",
    fontSize: themeFontSize.medium,
  },
  h5: {
    // fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.small,
  },
  h5Bold: {
    // fontFamily: "PoppinsMedium",
    fontWeight: "bold",
    fontSize: themeFontSize.small,
  },
  h6: {
    // fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.xsmall,
  },
  splashText: {
    // fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.splash,
    fontWeight: "bold",
    color: colors.neavyBlue,
  },
  welcomeContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: "15%",
    marginHorizontal: "5%",
  },
  themeContainerWhite: {
    flex: 1,
    paddingHorizontal: "5%",
    // marginBottom: "15%",
    backgroundColor: colors.white,
  },
  themeContainer: {
    flex: 1,
    paddingHorizontal: "5%",
    // marginBottom: "15%",
  },
  parentContainer: {
    flex: 1,
    paddingHorizontal: "5%",
    marginTop: "5%",
  },
  topMargin: {
    marginTop: "30%",
    maxWidth: "100%",
  },
  blueButton: {
    backgroundColor: colors.black,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 6,
    paddingBottom: 6,
    margin: 0,
    color: "#fff",
    borderRadius: 4,
  },
  blueButtonMain: {
    backgroundColor: colors.neavyBlue,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 8,
    paddingBottom: 8,
    margin: 0,
    color: "#fff",
    borderRadius: 4,
  },
  blueBtnText: {
    color: colors.white,
    // fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.large,
    textAlign: "center",
  },
  inActiveBtnText: {
    color: colors.black,
    // fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.large,
    textAlign: "center",
  },
  fullWidthBtn: {
    width: "100%",
    marginTop: 10,
  },
  input: {
    height: 40,
    maxWidth: 595,
    width: "100%",
    marginBottom: 19,
    borderColor: colors.lightgray,
    // borderWidth: 2,
    backgroundColor: "#FFFFFF",
    // borderRadius: 50,
    fontSize: themeFontSize.medium,
    color: colors.black,
    paddingLeft: 15,
    paddingRight: 15,
    justifyContent: "center",
  },
  searchInput: {
    height: 48,
    maxWidth: 595,
    width: "100%",
    marginBottom: 12,
    borderColor: "#E2E4E7",
    borderWidth: 2,
    backgroundColor: "#FFFFFF",
    borderRadius: 4,
    fontSize: themeFontSize.medium,
    color: colors.black,
    paddingLeft: 25,
    paddingRight: 25,
    justifyContent: "center",
  },
  inputNoBG: {
    borderColor: "#F1F3F8",
    borderBottomWidth: 1,
    marginBottom: 12,
    alignItems: "center",
    paddingVertical: 5,
  },
  dropdown: {
    width: "100%",
    // fontSize: themeFontSize.medium,
    // color: "#3F466F",
    color: colors.gray,
    // backgroundColor: "#FFFFFF",
  },
  dropdownWrapper: {
    width: "100%",
    height: 40,
    flexDirection: "row",
    position: "relative",
    backgroundColor: "#FFFFFF",
    paddingLeft: 8,
    paddingRight: 8,
    marginBottom: 8,
    alignItems: "center",
  },
  bottomDrop: {
    position: "absolute",
    right: 13,
    width: 13,
    height: 13,
    top: 12,
    resizeMode: "contain",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  relativeRow: {
    flexDirection: "row",
    position: "relative",
    alignItems: "center",
  },
  shadow: {
    shadowColor: "#ADB6D9",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.38,
    shadowRadius: 5,
    elevation: 5,
  },
  topBar: {
    flexDirection: "row",
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    paddingTop: "10%",
    paddingBottom: 10,
    backgroundColor: "#fff",
    zIndex: 1,
  },
  backbtn: {
    position: "absolute",
    left: 20,
    bottom: 12,
    zIndex: 2,
  },
  backArrow: {
    width: 20,
    height: 20,
    zIndex: 2,
  },
  nextbtn: {
    position: "absolute",
    right: 20,
    bottom: 12,
    zIndex: 2,
  },
  basketIcon: {
    width: "5%",
    alignItems: "center",
    paddingTop: 8,
  },
  saleEditBtn: {
    width: "10%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  vectorIcon: { width: 20, height: 20, resizeMode: "contain", marginRight: 20 },
  searchIcon: {
    width: 24,
    height: 24,
    resizeMode: "contain",
  },
  container: {
    maxWidth: 595,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  productQuantity: {
    borderWidth: 2,
    borderColor: "#CFD8EB",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 15,
    backgroundColor: colors.white,
  },
  quantityIcon: {
    paddingHorizontal: 12,
  },
  minusIcon: {
    width: 15,
    height: 15,
    resizeMode: "contain",
  },
  plusIcon: {
    width: 15,
    height: 15,
    resizeMode: "contain",
  },
  arrowIcon: {
    width: 30,
    height: 30,
    resizeMode: "contain",
  },
  quantity: {
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: "#CFD8EB",
  },
  quantityText: {
    paddingHorizontal: 5,
    textAlign: "center",
  },
  pickerText: {
    fontSize: themeFontSize.medium,
    color: colors.black,
  },
  activeBtn: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.neavyBlue,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  inActiveBtn: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  active: {
    backgroundColor: colors.neavyBlue,
  },
  categoriesList: {
    flexDirection: "row",
    paddingHorizontal: 2,
  },
  filterList: {
    maxWidth: 475,
    borderRadius: 10,
    // width: "100%",
    flex: 0,
    justifyContent: "center",
    marginTop: 5,
    marginBottom: 20,
    // marginHorizontal: "2%",
    paddingVertical: 8,
    backgroundColor: colors.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,

    elevation: 9,
  },

  editDelButton: {
    backgroundColor: colors.black,
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    borderRadius: 50,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 2,
  },
  rightCol: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    width: "53%",
  },

  centeredView: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  filterView: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  filterModal: {
    // flex: 1,
    height: 500,
    // justifyContent: "center",
    backgroundColor: "white",
    width: "100%",
    paddingHorizontal: "5%",
    paddingVertical: "5%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,

    elevation: 24,

    // bottom: 0,
    // position: "absolute",
    // zIndex: 1,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  keypadButton: {
    width: "32%",
    backgroundColor: "#ffffff",
    padding: 10,
    height: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 2,
    marginHorizontal: 2,
  },
  tabIcon: {
    width: 25,
    height: 25,
    tintColor: "#292929",
  },
  drawerIcon: {
    resizeMode: "contain",
    width: 20,
    height: 20,
    tintColor: colors.white,
  },
  notifiIcon: {
    resizeMode: "contain",
    width: 20,
    height: 20,
    tintColor: colors.neavyBlue,
  },
  BTposBtn: {
    width: 60,
    height: 60,
    position: "relative",
    borderRadius: 30,
    backgroundColor: colors.lightgray,
    justifyContent: "center",
    alignItems: "center",
    top: -20,
    // borderColor: "rgba(0,0,0,0.3)",
    // borderWidth: 5,
  },
  posBtn: {
    // justifyContent: "center",
    alignItems: "center",
  },
  posIcon: {
    tintColor: colors.neavyBlue,
  },
  checkbox: { width: 20, height: 20, borderRadius: 10 },
});
